<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UJ631HJ" failures="2" tests="4" name="EdgeTest" time="106.829" errors="0" timestamp="2022-03-11T00:58:22 IST">
  <testcase classname="test.VerifyApplicationHeader" name="verifyTaskPage" time="16.386">
    <failure type="java.lang.AssertionError" message="expected [http://localhost/tasks/otasklist.] but found [http://localhost/tasks/otasklist.do]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost/tasks/otasklist.] but found [http://localhost/tasks/otasklist.do]
at test.VerifyApplicationHeader.verifyTaskPage(VerifyApplicationHeader.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyTaskPage -->
  <testcase classname="test.TestClass" name="verifyTaskPage" time="16.499">
    <failure type="java.lang.AssertionError" message="expected [http://localhost/tasks/otasklist.] but found [http://localhost/tasks/otasklist.do]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost/tasks/otasklist.] but found [http://localhost/tasks/otasklist.do]
at test.TestClass.verifyTaskPage(TestClass.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyTaskPage -->
  <testcase classname="test.TestClass" name="verifyUsersPage" time="9.326"/>
  <testcase classname="test.VerifyApplicationHeader" name="verifyUsersPage" time="9.377"/>
</testsuite> <!-- EdgeTest -->
